#+title: eintr-solutions
#+author: cpmachado
#+startup: overview num


My solutions of the exercises of "An Introduction to Programming in Emacs Lisp"(eintr).


* List Processing
** Error Message Exercises
*** Exercise 1.11.1
Generate an error message by evaluating an appropriate symbol that is not within parentheses.
*** Exercise 1.11.2
Generate an error message by evaluating an appropriate symbol that is between parentheses.
*** Exercise 1.11.3
Create a counter that increments by two rather than one.
*** Exercise 1.11.4
Write an expression that prints a message in the echo area when evaluated.
#+begin_src emacs-lisp
  (message "Hello World")
#+end_src

#+RESULTS:
: Hello World

* Practicing Evaluation
** Evaluation Exercise
* Writing Defuns
** defun Exercises
* Buffer Walk Through
** Buffer Exercises
* More Complex
** optional Exercise
* Narrowing & Widening
** narrow Exercise
* car cdr & cons
** cons Exercise
* Cutting & Storing Text
** search Exercises
* List Implementation
** List Exercise
