#+title: eintr-solutions
#+author: cpmachado
#+startup: overview


My solutions of the exercises of "An Introduction to Programming in Emacs Lisp"(eintr).


* 1. List Processing
** 1.11 Error Message Exercises
*** Exercise 1.11.1
Generate an error message by evaluating an appropriate symbol that is not within parentheses.
*** Exercise 1.11.2
Generate an error message by evaluating an appropriate symbol that is between parentheses.
*** Exercise 1.11.3
Create a counter that increments by two rather than one.
*** Exercise 1.11.4
Write an expression that prints a message in the echo area when evaluated.
#+begin_src emacs-lisp
  (message "Hello World")
#+end_src

#+RESULTS:
: Hello World

* 2. Practicing Evaluation
** Evaluation Exercise
* 3. Writing Defuns
** defun Exercises
* 4. Buffer Walk Through
** Buffer Exercises
* 5. More Complex
** optional Exercise
* 6. Narrowing & Widening
** narrow Exercise
* 7. car cdr & cons
** cons Exercise
* 8. Cutting & Storing Text
** search Exercises
* 9. List Implementation
** List Exercise
